# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8624ba884ae7ae46702a31090e28bc0ab2a2c0ed458a9c0f30c40c2b3be4864024cab60bbd3f8ec5910daeea1ca03dd4796d455bc41f331133091426e542881d

test:
  secret_key_base: 034e243619da5e110b0dbe9eb22fd6f78948414313c6ad7ea57fdce50949e9cecd51690d2176eea502eae1c80e0d6357e946a1911c409e2846987a51e9472341

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
